### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by ZPWangZP** [TachibanaYoshino/AnimeGANv3#10]
作者你好，请问可以再次发布预训练模型吗，您提供的链接已经失效，万分感谢！

**Comment by discowang** [comment]
作者你好，请问AnimeGANv3_USA模式可以分享吗，万分感谢！

**Comment by TachibanaYoshino** [comment]
不好意思，已经半年过去了，论文还未被会议接收😔，我们正考虑重新投稿，所以这些算法相关的都没法开源，还望理解。我想等后面被接收录用后，应该会开源的。 github上有提到这些，你可以关注一下相关问题。
我觉得该模型当前属于商用性质，看是否有公司想买🤫

**Comment by discowang** [comment]
作者你好，如果是付费的话可以提供AnimeGANv3_USA模型或源码吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TachibanaYoshino/AnimeGANv3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 下午4:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TachibanaYoshino/AnimeGANv3] 关于预训练模型 (Issue #10)





 不好意思，已经半年过去了，论文还未被会议接收😔，我们正考虑重新投稿，所以这些算法相关的都没法开源，还望理解。我想等后面被接收录用后，应该会开源的。 github上有提到这些，你可以关注一下相关问题。 
 我觉得该模型当前属于商用性质，看是否有公司想买🤫 
 
 
 
 &gt; 在 2022年9月28日，15:43，discowang ***@***.***&gt; 写道： 
 &gt;  
 &gt; ﻿ 
 &gt; 作者你好，请问AnimeGANv3_USA模式可以分享吗，万分感谢！ 
 &gt;  
 &gt; — 
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe. 
 &gt; You are receiving this because you are subscribed to this thread.

**Comment by TachibanaYoshino** [comment]
> 作者你好，请问AnimeGANv3_USA模式可以分享吗，万分感谢！

Please check the license, please email.
