### ISSUE TITLE
Is there an onxx for paprika and shinkai style?

### ISSUE THREAD

**Issue by TebeZerias** [TachibanaYoshino/AnimeGANv3#5]
Im new to this and wondered if tehre was an onxx for pap and shin? Do i have to make one or something for those 2? and if so how do i go about making one?

**Comment by TachibanaYoshino** [comment]
Due to the lack of funds and machines, the follow-up plan for the v3 project has been stalled. When there may be funds and machines in the future, I will continue to release more anime stylized models. At least for now, it's a rather difficult thing for me. I have encountered great difficulties with my research.
